services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 9999:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - database
volumes:
  pgdata: null
  pgadmin: null
